### ISSUE TITLE
Smartcard reader + Android phone which doesn't have HCE

### ISSUE THREAD

**Issue by gaara87** [doc-rj/smartcard-reader#1]
Hey, this is not an issue with your code as much as a question about what would happen if i'm running the smart card reader the nexus 7 running 4.4+ and the other device is running 4.2 with only the possibility of beaming the data. 

Does it activate a one-way beam?

**Comment by doc-rj** [comment]
Hi gaara87,

This app interacts with the NFC chip's card emulation (CE) mode on the remote device. You can use any contactless (NFC) smartcard, physical or emulated. Android 4.2 (JellyBean) supported smartcard emulation for both Google Wallet and ISIS/Softcard in the US... For Google Wallet, however, instead of using HCE (host card emulation) like Kitkat and later do, it used an embedded, offhost secure element. Softcard used a SIM-based secure element and it still does today.

What device are you using and what are you trying to do?

**Comment by gaara87** [comment]
Well, i'm trying to do it with N7(4.4) and N5(4.2).

Running the smart card reader on the N7 to make it act as an NFC terminal. 

The N5 is a device which DOESN'T have HCE. So the only way of transferring data through NFC is through BEAM. 

You have mentioned in you reply that the app interacts with CE mode on the remote device. Agreed. But what happens if there isn't one? :)

**Comment by doc-rj** [comment]
The N5 NFC does support card emulation mode. With Android 4.2, it doesn't use HCE, but it does use an offhost CE mode (where the card credentials are kept in an offhost secure element). Sorry if I wasn't clear about that in my previous reply.
